### ISSUE TITLE
Tests fail with import error due to missing PYTHONPATH in executionEnvironments

### ISSUE THREAD

**Issue by alexander-born** [nvim-neotest/neotest-python#42]
The projects at work use execution environments with extra paths which are defined in a pyproject.toml file.

Example of [pyproject.toml](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#sample-pyprojecttoml-file):

```toml
[tool.pyright]
include = ["src"]
exclude = ["**/node_modules",
    "**/__pycache__",
    "src/experimental",
    "src/typestubs"
]
ignore = ["src/oldstuff"]
defineConstant = { DEBUG = true }
stubPath = "src/stubs"
venv = "env367"

reportMissingImports = true
reportMissingTypeStubs = false

pythonVersion = "3.6"
pythonPlatform = "Linux"

executionEnvironments = [
  { root = "src/web", pythonVersion = "3.5", pythonPlatform = "Windows", extraPaths = [ "src/service_libs" ] },
  { root = "src/sdk", pythonVersion = "3.0", extraPaths = [ "src/backend" ] },
  { root = "src/tests", extraPaths = ["src/tests/e2e", "src/sdk" ]},
  { root = "src" }
]
```

In order to make the test not fail on imports I need to modify the PYTHONPATH with both the root and all the extraPaths for the correct executionEnvironment.
